CREATE TABLE Pistas ( 
    id_pista INT AUTO_INCREMENT PRIMARY KEY, 
    deporte VARCHAR(255), 
    num_pista INT, 
    techada BOOLEAN, 
    iluminacion VARCHAR(255), 
    tipo VARCHAR(255), 
    cesped VARCHAR(255), 
    automatizada BOOLEAN, 
    duracion_partida INT, 
    hora_inicio TIME, 
    hora_fin TIME, 
    socio_tiempo_reserva INT, 
    socio_tiempo_cancelacion INT, 
    socio_precio_con_luz FLOAT, 
    socio_precio_sin_luz FLOAT, 
    no_socio_tiempo_reserva INT, 
    no_socio_tiempo_cancelacion INT, 
    no_socio_precio_con_luz FLOAT, 
    no_socio_precio_sin_luz FLOAT, 
    efectivo BOOLEAN,
    monedero BOOLEAN,
    tarjeta BOOLEAN,
    bono BOOLEAN,
    nombre_patrocinador VARCHAR(255), 
    imagen_patrocinador VARCHAR(255), 
    vestuario BOOLEAN, 
    duchas BOOLEAN, 
    imagenes_pista TEXT, 
    descripcion VARCHAR(255), 
); 