CREATE TABLE Pistas ( 
    id_pista INT AUTO_INCREMENT PRIMARY KEY, 
    deporte VARCHAR(255), 
    num_pista INT, 
    techada BOOLEAN, 
    iluminacion VARCHAR(255), 
    tipo VARCHAR(255), 
    cesped VARCHAR(255), 
    automatizada BOOLEAN, 
    duracion_partida INT, 
    hora_inicio TIME, 
    hora_fin TIME, 
    socio_tiempo_reserva INT, 
    socio_tiempo_cancelacion INT, 
    socio_precio_con_luz FLOAT, 
    socio_precio_sin_luz FLOAT, 
    no_socio_tiempo_reserva INT, 
    no_socio_tiempo_cancelacion INT, 
    no_socio_precio_con_luz FLOAT, 
    no_socio_precio_sin_luz FLOAT, 
    efectivo BOOLEAN,
    monedero BOOLEAN,
    tarjeta BOOLEAN,
    bono BOOLEAN,
    nombre_patrocinador VARCHAR(255), 
    imagen_patrocinador VARCHAR(255), 
    vestuario BOOLEAN, 
    duchas BOOLEAN, 
    imagenes_pista TEXT, 
    descripcion VARCHAR(255), 
); 
CREATE TABLE usuarios ( 
    id_usuario INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255),
    apellidos VARCHAR(255),
    sexo VARCHAR(6),
    DNI VARCHAR(9),
    lada VARCHAR(3),
    telefono VARCHAR(9),
    email VARCHAR(255),
    empadronamiento VARCHAR(255),
    comunidad_de_vecinos VARCHAR(255),
    direccion VARCHAR(255),
    codigo_postal INT(5),
    localidad VARCHAR(255),
    provincia VARCHAR(255),
    comunidad VARCHAR(255),
    nick VARCHAR(255),
    nivel VARCHAR(5),
    posicion VARCHAR(255),
    marca_pala VARCHAR(255),
    modelo_pala VARCHAR(255),
    juegos_semana VARCHAR(2),
    contrasena VARCHAR(255),
    foto VARCHAR(255),
    fecha_registro DATETIME,
    validate_email BOOLEAN); 
 

CREATE TABLE proveedores ( id_proveedor INT AUTO_INCREMENT PRIMARY KEY,
    tipo VARCHAR(255),
    cif_nif VARCHAR(9),
    direccion_fiscal VARCHAR(255),
    codigo_postal_fiscal INT(5),
    localidad_fiscal VARCHAR(255),
    provincia_fiscal VARCHAR(255),
    comunidad_fiscal VARCHAR(255),
    codigo_iban VARCHAR(255),
    certificado_cuenta VARCHAR(255),
    nombre VARCHAR(255),
    apellidos VARCHAR(255),
    fijo VARCHAR(20),
    email VARCHAR(255),
    lada VARCHAR(3),
    telefono VARCHAR(15),
    nombre_comercial VARCHAR(255),
    direccion VARCHAR(255),
    codigo_postal INT(5),
    localidad VARCHAR(255),
    provincia VARCHAR(255),
    comunidad VARCHAR(255),
    contrasena VARCHAR(255),
    foto VARCHAR(255),
    fecha_registro DATETIME,
    validate_email BOOLEAN ); 